version : '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2.3
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge