spring:
  profiles:
    active: ${env}
  main:
    banner-mode: "off"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /

cache:
  evict:
    time: 60000